sonar.projectKey=omarosama16_Hospital-Appointment-Booking-System-Using-Cpp
sonar.organization=omarosama16

sonar.sources=src,include
sonar.tests=tests
sonar.sourceEncoding=UTF-8

# Use build-wrapper output (NOT compile-commands — only one is allowed)
sonar.cfamily.build-wrapper-output=bw-output

sonar.exclusions=**/build/**,**/cmake-build/**,**/bw-output/**
sonar.test.inclusions=tests/**
