sonar.projectKey=omarosama16_Hospital-Appointment-Booking-System-Using-Cpp
sonar.organization=omarosama16
sonar.sources=src,include
sonar.tests=tests
sonar.sourceEncoding=UTF-8
sonar.cfamily.compile-commands=bw-output/compile_commands.json
sonar.exclusions=**/build/**,**/cmake-build/**,**/bw-output/**
sonar.test.inclusions=tests/**
