sonar.projectKey=omarosama16_Hospital-Appointment-Booking-System-Using-Cpp
sonar.organization=omarosama16

sonar.sources=src,include
sonar.tests=tests
sonar.sourceEncoding=UTF-8

# 🔴 Important: exclude build noise
sonar.exclusions=build/**,CMakeFiles/**,**/*.o,**/*.exe,**/*.a,**/*.so

# 🔴 Helps Sonar ignore compiled artifacts
sonar.cfamily.build-wrapper-output=bw-output
