name: C++ CI + CMake + SonarCloud

on:
  push:
    branches: ["*"]
  pull_request:

jobs:
  build-analyze:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ cmake make git wget unzip


    - name: Configure project
      run: |
        cmake -S . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

    - name: Install Build Wrapper
      run: |
        wget https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
        unzip build-wrapper-linux-x86.zip
        echo "$PWD/build-wrapper-linux-x86" >> $GITHUB_PATH

    - name: Build project (wrapped)
      run: |
        mkdir -p bw-output
        build-wrapper-linux-x86/build-wrapper-linux-x86-64 \
          --out-dir bw-output \
          cmake --build build -j 2


    - name: Run app
      run: |
        timeout 3s ./build/app || true


    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v2
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=omarosama16_Hospital-Appointment-Booking-System-Using-Cpp
          -Dsonar.organization=omarosama16
          -Dsonar.sources=src
          -Dsonar.sourceEncoding=UTF-8
          -Dsonar.cfamily.compile-commands=build/compile_commands.json
          -Dsonar.cfamily.build-wrapper-output=bw-output
          -Dsonar.exclusions=build/**,bw-output/**
